[build]
  # 빌드 명령어
  command = "npm run build"

  # 빌드 결과물 디렉토리 (static export의 경우 out 폴더)
  publish = "out"

[build.environment]
  # Node.js 버전 지정
  NODE_VERSION = "18"

# SPA fallback 설정 (Next.js static export용)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 헤더 설정 (보안 및 성능)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 정적 파일 캐싱
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
